image: centos-7-build:latest
   

stages:
- test
- build

test:linux:
    stage: test
    script: make && make clean
    tags:
    - linux
    - git

build:linux:
    stage: build
    script: make
    dependencies:
    - test:linux
    tags:
    - linux
    - git
    artifacts:
        paths:
        - samp-timestamp
        expire_in: 1 month
